apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pg-selector.fullname" . }}
  labels:
    {{- include "pg-selector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      {{- include "pg-selector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.controller.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pg-selector.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.controller.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pg-selector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.controller.podSecurityContext | nindent 8 }}
      containers:
        - name: manager
          args:
          {{- with .Values.controller.extraArgs }}
          {{ toYaml . | nindent 10 }}
          {{- end }}

          {{- with .Values.controller.env }}
          {{ toYaml . | nindent 10 }}
          {{- end }}

          {{- with .Values.controller.envFrom }}
          {{ toYaml . | nindent 10 }}
          {{- end }}

          command:
            - /manager
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag | default (printf "v%s" .Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}

          # TODO: Good first issue
          livenessProbe: {}
          readinessProbe: {}

          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.controller.securityContext | nindent 12 }}

          volumeMounts:
            {{- with .Values.controller.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        {{- with .Values.controller.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

