# Default values for pg-selector.

nameOverride: ""
fullnameOverride: ""

# Following custom ClusterRole is a place where to add the type of resources
# allowed to be treated by PG Selector.
customClusterRole:
  # Specifies whether a custom clusterRole should be created
  create: true

  # Annotations to add to the clusterRole
  annotations: {}

  # A set of rules as documented here : https://kubernetes.io/docs/reference/access-authn-authz/rbac/
  rules:
  - apiGroups: ['']
    resources:
      - endpointslices
      - pods
      - services
    verbs: &customClusterRoleVerbsSpec
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  #- apiGroups: [ 'discovery.k8s.io/v1' ]
  #  resources:
  #    - endpointslices
  #  verbs: *customClusterRoleVerbsSpec

  clusterRoleBinding:
    # Annotations to add to the clusterRoleBinding
    annotations: {}

# TODO
controller:

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: { }
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: "pg-selector"

  replicaCount: 1

  image:
    repository: ghcr.io/freepik-company/pg-selector
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  imagePullSecrets: []

  # Extra args to pass to the controller.
  # Ref: https://github.com/freepik-company/pg-selector?tab=readme-ov-file#flags
  # Example:
  # - --events-per-second=100
  extraArgs: []

  # Define a list of environment variables used inside the controller
  # Ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#use-configmap-defined-environment-variables-in-pod-commands
  # - name: SPECIAL_LEVEL_KEY
  #   valueFrom:
  #     configMapKeyRef:
  #       name: special-config
  #       key: SPECIAL_LEVEL
  env: []

  # Define a list of environment variables coming from a ConfigMap or a Secret
  # - configMapRef:
  #     name: special-config
  # Ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-container-environment-variables
  envFrom: []

  # Define a list of extra volumes to mount into the controller
  # Ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#populate-a-volume-with-data-stored-in-a-configmap
  extraVolumes: []
  extraVolumeMounts: []

  podAnnotations: {}

  podSecurityContext: {}

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}
